Repository Izzy-Irvine/pandora-jam-2024, pull requests merged in 2024-11, with the labels that each got.

#24 audio: add enemy death sound effect
  scenes/enemy/enemy.tscn
  scripts/enemy.gd
Labels: help wanted, gumball head, 🖕...

#25 i added a death screen
  scenes/game_over_screen.tscn
  scripts/game_over_button.gd
  scripts/player.gd
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, skibidi, lgbtq

#28 Feet/lots of things
  scenes/enemy/enemy.tscn
  scenes/level/level.tscn
  scenes/main.tscn
  scenes/projectiles/bullet.tscn
  scenes/ui.tscn
  scripts/bullet.gd
  scripts/enemy.gd
  scripts/main.gd
  scripts/player.gd
Labels: lgbtq
